### ISSUE TITLE
Lobby Screen: grid was going to be 6x4, not 6x6 

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#12]
My understanding was that the Lobby Screen grid was going to be 6 columns by 4 rows, not the 6x6 currently implemented. We currently have examples of 1x2, 1x4 and 2x2 widget areas.

Further:

a) we have yet to display any widget in less than two rows, so we might want to make that 6 columns by 2 (double height) rows.

b) in the prototype we stole 60px from the top for a banner.

**Comment by abrahammartin** [comment]
Fixed in https://github.com/ijl20/tfc_web/commit/1a577592adfff2600c5546508831d955e004c351
