### ISSUE TITLE
Lobby Screen: Need generic styles for widget elements

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#13]
We need some generic styles for use in widgets to promote visual consistency.

Before creating them, we need to decide if we are going to use semantic HTML (\<h1\>, \<h2\>, etc. - @jw35's natural instinct) or exclusively <divs>'s with classes (@ijl20's preference). 

Given a decision, I've no problem doing this but a) I'll have to re-learn more CSS to do it and b) you'll get my idea of design...

**Comment by abrahammartin** [comment]
I'd use the material design ones, as the rest of the app does: https://getmdl.io/components/index.html

**Comment by jw35** [comment]
Sounds like a plan. I've taken a  quick look and seem to be missing the 'how do I actually use it' part, bit it may become clear in use.

I think we will still need some policy for ow we use MDL if the widgets are going to look even vaguely consistent.

**Comment by abrahammartin** [comment]
I believe this is now obsolete, closing the issue.
