### ISSUE TITLE
Lobby screen: XSS protection for message_area widgit

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#14]
Currently message_area takes raw HTML and inserts it into the Lobby Screen page. This opens the system to XSS attack by Lobby Screen managers, and to general layout disaster. 

Either we have to stop using HTML (but note that Markdown is no better because it can include raw HTML) or someone has to sanitise the message.

**Comment by abrahammartin** [comment]
I'd try to avoid to reinvent the wheel and use one of the WYSIWYG editors out there, that may already have solved this.

**Comment by abrahammartin** [comment]
I've been doing some research about this and I though that bleach from Mozilla was the best option, see: https://github.com/mozilla/bleach

But then while I was implementing it I tough it was a bad idea as I was including a adding quite a lot of exceptions in de backend for only 1 particular widget, so it felt I wasn't doing it right, and it doesn't keep the framework and the widgets independent.

After thinking about alternatives, I think that the best way is doing it inside the widget and use a sanitise javascript library before loading the content into the widget div. One good options seems to be: https://github.com/punkave/sanitize-html

@jw35 ?

**Comment by jw35** [comment]
This is worse/harder then it looks 😢 

sanitize-html is fine for making a random JavaScript string safe(ish) for inserting directly with innerHTML (and it's jQuery friends like html())

But further back in the process we have the bigger problem of including random strings as parameters in the JavaScript that instantiates the widgets. For example 

```html
<script>
 // Note we must instatiate RTMonitorAPI before widgets
 var RTMONITOR_API = new RTMonitorAPI();
 var widget = [];
    
 widget.push(new MessageArea(
 {'container': 'widget-0', 'static_url': '/static_web/smartpanel/widgets/message_area/'},
 {"title": "Title", "message": "<script>alert(document.cookie);</script>"}
 ));

// Other stuff

</script>
```

explodes, apparently because the HTML parser sees the embedded </script>. Rule 3 of OWASP's [XSS Prevention Cheat Sheet](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.233_-_JavaScript_Escape_Before_Inserting_Untrusted_Data_into_JavaScript_Data_Values) acknowledges this, and seems to go further by saying that you can 

1. Only safely include untrusted data inside quoted strings; _and_
2. Only do that if you first violently escape it

There are lots of StackOverflow questions in this area. Many seem to be dealing with unexpected HTML or JavaScript escaping and seem worryingly to be resolving their immediate problems with copious use of `|safe`.

Since we can't easily JavaScript-escape (presumably with `|escapejs`) the individual strings inside the Json I think our best approach may be to have the parameters appear as an escaped Json string in the HTML, and to use JavaScript to un-escape it and parse the resulting Json to get our data structure back.

So something like this (untested):

```
widget.push(new {{ value.configuration.widget|title|remove_underscore }}(
                {'container': 'widget-{{ key }}', 'static_url': '{% static 'smartpanel/widgets' %}/{{ value.configuration.widget }}/'},
                JSON.parse(unescape({{ value.configuration.data|jsonify|escapejs }}))
            ));
```

I'd still need sanitize-html to support limited HTML markup in messages, and I need to check every other variable substitution to check it doesn't allow HTML to be inserted (which I think means avoiding innerHTML() and friends like the plague).

@abrahammartin?
