### ISSUE TITLE
Review access to the Transport API endpoints

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#143]
We should review what Transport API endpoints we which to provide/support

**Comment by abrahammartin** [comment]
They already do have access to this endpoint via the real time bus map as the map is doing an ajax call to these endpoints every few seconds (or to RT monitor in the other real time bus map). We can't avoid these to be public, otherwise we couldn't show the real time map.

**Comment by jw35** [comment]
I *think* that medium term the functionality of this endpoint can be replaced by the RTmonitor's web sockets interface at which point we can remove it from the API.

**Comment by jw35** [comment]
Closed by eb6c26eca2e2109c89d651d114c52029932495a1
