### ISSUE TITLE
Lobby Screen: framework needs to include widget CSS files

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#15]
Most widgets come with a CSS file. Part of the framework<->widget contract is that such files, if they exist, will be included in the page displaying the widget. Currently they aren't.

**Comment by abrahammartin** [comment]
We are now loading CSS files via requirements.json, documented at https://github.com/ijl20/tfc_web/tree/dashboard/tfc_web/static/smartpanel/widgets/README.md
