### ISSUE TITLE
Lobby Screen: additional JavaScript needed for some widgets

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#16]
Some widgets - all the map ones and some others like the Twitter Timeline - need 3rd party libraries and/or .CSS files loading once into the page that displays them. Currently we have no way of doing this short of editing the layout.html template.

**Comment by jw35** [comment]
I've briefly confirmed that the traffic and twitter widgets work providing their supporting Javascript libraries are loaded.

**Comment by abrahammartin** [comment]
widgets should have a package.json to specify dependencies: https://docs.npmjs.com/files/package.json

**Comment by jw35** [comment]
Sounds good. For the life of me I can't see how to use a package.json file to specify, for example, that twitter_timeline needs `https://platform.twitter.com/widgets.js`. Can you point me at an example?

**Comment by jw35** [comment]
REsolved by the introduction of the `requirements.json` file into the widget spec and subsequent implementation.
