### ISSUE TITLE
IntegrityError deleting an in-use layout

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#168]
If you try to delete a layout that's assigned to a display you get an IntegrityError:

    update or delete on table "smartpanel_layout" violates foreign key constraint "smartpanel_display_layout_id_0e8120ad_fk_smartpanel_layout_id" on table "smartpanel_display" DETAIL:  Key (id)=(1) is still referenced from table "smartpanel_display".

**Comment by abrahammartin** [comment]
I'm showing an error message now instead, see 716c53f7148a2c2411522e95bbdc3245963411f5
The alternative is delete the display or leave the display broken without a layout. Which is a tricky decision to make if the layouts go public. And layouts are used by displays that are not yours. Probably we need to discuss.
