### ISSUE TITLE
Slow API

### ISSUE THREAD

**Issue by abrahammartin** [ijl20/tfc_web#22]
@ijl20 reports that we are getting 502 for some API requests. For example: /transport/api/journeys_by_time_and_stop/?stop_id=0500CCITY111&datetime_from=2018-02-12T08%3A53%3A41&expand_journey=true

This is due that the time it takes the database to respond is longer than the nginx timeout. This is because there are a lot of buses running through that stop in a day. This can only be replicated with expand_journey=true, with expand_journey=false it responds in time.

A possible solution can be, having, by default nresults=10 unless the user changes it for the journeys_by_time_and_stop call: http://smartcambridge.org/transport/api/docs/#journeys_by_time_and_stop

It's a way of paginating, and reducing the load of the database.

Opinions? @jw35 @ijl20

**Comment by jw35** [comment]
On 11 Feb 2018, at 08:44, Abraham Martin <notifications@github.com<mailto:notifications@github.com>> wrote:

Opinions? @jw35<https://github.com/jw35> @ijl20<https://github.com/ijl20>

I was planning to do that anyway, but we need some way to reliably ask for ‘next 10’, or ‘next 10 from this one’. Just using time as a primary key won’t work, because two departures from the same stop at the same time are not unknown.

Jon

--
Jon Warbrick

**Comment by abrahammartin** [comment]
journeys_by_time_and_stop now support pagination. You will get a "next" parameter in the response which contains the url you have to call next, to get the following entries for that stop. Example: http://tfc-app3.cl.cam.ac.uk/transport/api/journeys_by_time_and_stop/?stop_id=0500CCITY484&datetime_from=2018-02-19%2009:55:01&nresults=10&expand_journey=false

**Comment by jw35** [comment]
I mentioned Phil Hazel's memoir. Good news: I found a URL for it. Bad news: it's on people.ds.cam.ac.uk that UIS just shut down:

http://people.ds.cam.ac.uk/ph10/CIHK.pdf

Fortunately the wayback machine seems to have a copy:

https://web.archive.org/web/20190823212727/http://people.ds.cam.ac.uk/ph10/CIHK.pdf

FYI.

Jon.

-- 
Jon Warbrick
Adaptive Cities Programme, University of Cambridge

**Comment by jw35** [comment]
On 2019-10-01 15:42, Jon Warbrick wrote:
> Bad news: it's on people.ds.cam.ac.uk that UIS just shut down:

Without even a tombstone!!!!

> https://web.archive.org/web/20190823212727/http://people.ds.cam.ac.uk/ph10/CIHK.pdf

Thanks; looks interesting.
