### ISSUE TITLE
Naming things: lobby_screen/dashboard/smartpanel

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#29]
It looks as though we are heading towards branding the thing I call a lobby_screen and @abrahammartin calls a dashboard as 'SmartPanel'. Before it's too late, we might want to consider moving http://<whatever>/dashboard/ to http://<whatever>/smartpanel/

**Comment by abrahammartin** [comment]
agree

**Comment by jw35** [comment]
OK. As a small step I've edited the 'Lobby Screen' label to read SmartPanel. It doesn't look like you can rename milestones.

**Comment by abrahammartin** [comment]
Pr #36 submitted
