### ISSUE TITLE
Some web pages for the 'SmartPanel' (aka Lobby Screen) development

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#30]
For release we are going to want some information pages about the 'SmartPanel' (aka Lobby Screen) development that we can link to from the Panels themselves. In principle these might cover a multitude of functions:

* Further info for interested users
* Somewhere to solicit feedback from users
* A place to put all the acknowledgements that the various otherwise free services we are using require
* Documentation for panel administrators
* [...]

though to start with we might just have a single page...

It seems to me that http://smartcambridge/smartpanel/info/ might be a good choice (on the assumption that we adopt the name change proposed in #29). So that probably means doing everything in Django templates within tfc_web. Does that sound sane?

**Comment by abrahammartin** [comment]
Totally agree
