### ISSUE TITLE
Disagreement over SmartPanel widget constructor signature

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#33]
Commit 6d9d7b5 introduces a different fix for static_url from the one implemented in https://github.com/jw35/acp_lobby_screen and documented in https://github.com/jw35/acp_lobby_screen/blob/master/widgets.md

[I thought I'd already reported this, but if so I can't find it...]

**Comment by abrahammartin** [comment]
duplicated from #35

**Comment by jw35** [comment]
This isn't a duplicate of #35!

This is about the fact that (the spec)[https://github.com/ijl20/tfc_web/blob/dashboard/tfc_web/static/smartpanel/widgets/README.md] says

> It will recieve two parameters:
>
> * A JavaScript Object conventionally named params containing static configuration parameters for the widgit:
> 
>     * container: The string DOM id of the page element into which the widget's content should be placed. This is guaranteed to be unique within any particular SmartScreen instance and so can be used as a base for other globally-unique names if needed.
>
>     * static_url: a URL coresponding to the widget directory (i.e. the one containing the JavaScript file). This allow the JavaScript to access other resources in the widget directory without having to hard-code URLs. Hard-coded URL's must not be used to allow SmartScreens to be setup under a variety of URL prefixes.
>
> * A JavaScript object conventionally named config containing parameters for a particular instance of the widget as defined in the <name>-schema.json file. 

whereas you are calling them like this:

> widget.push(new StationBoard('widget-0', {'station': 'CBG', 'offset': 0}, '/static_web/smartpanel/widgets'));

@ijl20 favours the former. I don't mind, but you two need to come to an agreement.

**Comment by jw35** [comment]
Fixed in 5c9459 in the jw35-reimport-widgets branch

**Comment by jw35** [comment]
Will be closed by PR #52

**Comment by jw35** [comment]
Closed by PR #52
