### ISSUE TITLE
Changes to requirements.json format

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#34]
Elsewhere (https://github.com/jw35/acp_lobby_screen/issues/1) I proposed the following:

1. Make the key in the 'scripts' objects 'src' rather than URL. This has the advantages that it matches usage in the <script> tag.

2. Also support an integrity element for stylesheets by allowing the "stylesheets" section to contain objects as well as plain strings. In this case for consistency with the HTML link tag the keys should probably be "href" and "integrity".

The current requirements.json files are written on the expectation that we make this change.

**Comment by abrahammartin** [comment]
PR #37 submitted

**Comment by abrahammartin** [comment]
PR #37 has been merged, so closing the issue
