### ISSUE TITLE
Need a decision as to where static_url points

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#35]
Currently the temporary framework passes the URL prefix for the widget directory itself as static_url. The tfc_web version passes a URL prefix for the directory one layer higher up (the one containing the widget directories themselves). 

Both are usable. The former is slightly easier for widget authors and matches what the widget specification currently says, but is slightly harder for the framework.

We need a decision on which to use.

**Comment by abrahammartin** [comment]
I also thing the former is easier

**Comment by jw35** [comment]
I think #34 isn't a pull request, so I don't know what to agree to...

**Comment by jw35** [comment]
... but I agree that the former (static_url points to to the widget directory itself) is preferable.

**Comment by abrahammartin** [comment]
Mmmm, that wasn't very helpful. Take a look at: https://github.com/ijl20/tfc_web/blob/3bf35c4f77bb3b006f4a4d906bf3c38430f968ff/tfc_web/smartpanel/templates/smartpanel/layout.html#L42

**Comment by jw35** [comment]
Looks right, though I'm assuming it's not yet on tfc-app3 because its not what's happening there.

**Comment by abrahammartin** [comment]
Good, agreed, closing then.
