### ISSUE TITLE
Review panel for IE/Edge/Firefox/Safari

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#48]
While the main target is Chrome on an HD screen, we really need things to work at least for desktop preview in other browsers.

**Comment by abrahammartin** [comment]
I have tried Windows 10 and Chrome and Edge and the tfc-app4 example from @jw35  works on both

**Comment by jw35** [comment]
I am, frankly, amazed. I fear IE will be more problematic and will probably be more important (corporate desktops, etc.).

--
Jon Warbrick

On 2 Apr 2018, at 11:40, Abraham Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


I have tried Windows 10 and Chrome and Edge and the tfc-app4 example from @jw35<https://github.com/jw35> works on both

**Comment by jw35** [comment]
Mac Firefox and Safari seem OK on brief inspection

**Comment by jw35** [comment]
For me on Edge (all versions), stop_timetable fails, complaining "Object doesn't support property or method 'append' in stop_timetable.js (1244,20)"

On IE 11, traffic_map reports "Invalid character" in traffic_map.js (66,12), and stop_timetable reports "Invalid character" in stop_timetable.js (845,22)

**Comment by jw35** [comment]
If we are serious about cross-browser testing we may want to use [BriowserStack](https://www.browserstack.com/). It is possible we could use it for free if we

* Have a publicly accessible source code and a valid open source license.
* Post their logo on our GitHub or website, hyperlinked to BrowserStack.com.

https://www.browserstack.com/open-source?ref=resources_banner

Are we interested @ijl?

**Comment by jw35** [comment]
IJL reports done
