### ISSUE TITLE
Complicated parameter requirements don't fit

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#63]
The current widget config interface (which we are probably replacing which would make this issue moot) can't cope with complicated parameter requirements such as those for stop_timetable: 

![image](https://user-images.githubusercontent.com/2385623/38093702-a723311a-3363-11e8-9625-4250aae5ce6f.png)

**Comment by abrahammartin** [comment]
Better to use the configuration page I designed initially? 

http://tfc-app3.cl.cam.ac.uk/smartpanel/layout/<id>/config/

**Comment by jw35** [comment]
Yes, that (or something like it) is much better. I'm still getting lost between all the various pages.

I suggest we leave this issue open until we (you) have sorted the final configuration interface.

**Comment by jw35** [comment]
Closed by PR #84
