### ISSUE TITLE
transport api documentation - time fields

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#7]
For the documentation of all the 'time' fields, it would be useful to mention what formats are accepted (by the looks of it 'anything acceptable to https://dateutil.readthedocs.io/en/stable/parser.html), and also to be clear that the time fields are actually date&time.

**Comment by abrahammartin** [comment]
better documented now in: http://tfc-app3.cl.cam.ac.uk/transport/api/docs/#journeys_by_time_and_stop
