### ISSUE TITLE
journeys_by_time_and_stop documentation - days_of_week result field

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_web#9]
What does the "days"of_week" results field represent? 

This query

```
coreapi action journeys_by_time_and_stop list -p stop_id=0500CCITY424 -p time_from=2018-01-25T13:45:00 -p time_to=2018-01-25T15:00:00
```

returns results with "days"of_week" set to "Saturday", "Monday Tuesday Wednesday Thursday Friday", "Friday", "Thursday", "", and "Wednesday".

How much OperatingProfile filtering is happening to these results?

**Comment by abrahammartin** [comment]
It expands OperatingProfile to list the days it refers to. For example Monday to Friday expands to  "Monday Tuesday Wednesday Thursday Friday". That is for making queries faster as we can search buses that run on Wednesday by saying days_of_week__contains="Wednesday"
